version: '3'
services:
  postgres-sql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: silvia05
      POSTGRES_DB: Distribuida
    ports:
        - 5433:5432

#aplicacion
  authors-service:
    image: silviaq/app-authors:2.0.0
    environment:
      DB_USER: postgres
      DB_PASSWORD: silvia05
      DB_URL: jdbc:postgresql://postgres-sql:5432/Distribuida
   #   SERVER_PORT: 80
    depends_on:
      - postgres-sql
    deploy:
      replicas: 1
    ports:
  #    - 80:80
     - 7002:7002